
/////////////////////////////////////////////////////////////
//
// Source file for Hpaned
//
//    This file is generated by RapidApp 1.2
//
//    This class is derived from HpanedUI which 
//    implements the user interface created in 
//    RapidApp. This class contains virtual
//    functions that are called from the user interface.
//
//    When you modify this source, limit your changes to 
//    modifying the sections between the
//    "//---- Start/End editable code block" markers
//
//    This will allow RapidApp to integrate changes more easily
//
//    This class is a ViewKit user interface "component".
//    For more information on how components are used, see the
//    "ViewKit Programmers' Manual", and the RapidApp
//    User's Guide.
/////////////////////////////////////////////////////////////

#include "Hpaned.h"
#include <Vk/VkEZ.h>
#include <Sgm/HPanedW.h> 
#include <Xm/BulletinB.h> 
#include <Xm/Scale.h> 
#include <Xm/ToggleB.h> 
#include <Vk/VkResource.h>


// Externally defined classes referenced by this class:

#include <Inventor/Xt/viewers/SoXtExaminerViewer.h>
#include <Inventor/So.h> // Includes ALL Inventor headers.
                         // Replace for efficiency and faster compilaton
#include <Vk/VkWindow.h>
#include <Vk/VkMenuBar.h>
#include <Vk/VkSubMenu.h>


extern void VkUnimplemented ( Widget, const char * );

///////////////////////////////////////////////////////////////////////////////
// The following non-container elements are created by HpanedUI and are
// available as protected data members inherited by this class
//
//  XmScale		    _speedScale
//  XmScale		    _scale
//  XmToggleButton		    _autoToggle
//
// The following components are created by HpanedUI and are
// available as protected data members inherited by this class
//
//  SoXtExaminerViewer		   *_viewer
//
///////////////////////////////////////////////////////////////////////////////


//---- Start editable code block: headers and declarations


//---- End editable code block: headers and declarations



//---- Hpaned Constructor

Hpaned::Hpaned(const char *name, Widget parent) : 
                   HpanedUI(name, parent) 
{ 
    // This constructor calls HpanedUI(parent, name)
    // which calls HpanedUI::create() to create
    // the widgets for this component. Any code added here
    // is called after the component's interface has been built

    //---- Start editable code block: Hpaned constructor


    //---- End editable code block: Hpaned constructor



}    // End Constructor



Hpaned::Hpaned(const char *name) : 
                   HpanedUI(name) 
 { 
    // This constructor calls HpanedUI(name)
    // which does not create any widgets. Usually, this
    // constructor is not used

    //---- Start editable code block: Hpaned constructor 2


    //---- End editable code block: Hpaned constructor 2



}    // End Constructor



Hpaned::~Hpaned()
{
    // The base class destructors are responsible for
    // destroying all widgets and objects used in this component.
    // Only additional items created directly in this class
    // need to be freed here.

    //---- Start editable code block: Hpaned destructor


    //---- End editable code block: Hpaned destructor



}    // End Destructor


const char * Hpaned::className() // classname
{
    return ("Hpaned");
} // End className()


void Hpaned::autoToggleCB ( Widget w, XtPointer callData )
{
    //---- Start editable code block: Hpaned autoToggleCB

    XmToggleButtonCallbackStruct *cbs = (XmToggleButtonCallbackStruct*) callData;

    //--- Comment out the following line when Hpaned::autoToggleCB is implemented:

    //::VkUnimplemented ( w, "Hpaned::autoToggleCB" );

    extern SoTimerSensor *autoMotionSensor;
    if ((int) EZ(_autoToggle)) autoMotionSensor->schedule();
    else autoMotionSensor->unschedule();


    //---- End editable code block: Hpaned autoToggleCB

}    // End Hpaned::autoToggleCB()


void Hpaned::speedScaleCB ( Widget w, XtPointer callData )
{
    //---- Start editable code block: Hpaned speedScaleCB

    XmScaleCallbackStruct *cbs = (XmScaleCallbackStruct*) callData;

    //--- Comment out the following line when Hpaned::speedScaleCB is implemented:

    //::VkUnimplemented ( w, "Hpaned::speedScaleCB" );

    extern int speed;
    speed = EZ(_speedScale);


    //---- End editable code block: Hpaned speedScaleCB

}    // End Hpaned::speedScaleCB()


void Hpaned::openFile( const char * filename )
{
    // This member function is called after the user has selected a new
    // file to be opened. The name of the file is given by the 
    // filename argument. You can get additional information by  
    // examining the state of theFileSelectionDialog object.



    //---- Start editable code block: Hpaned openFile

    //--- Comment out this line when this function is implemented:

  //::VkUnimplemented ( NULL, "Hpaned::openFile" );




    //---- End editable code block: Hpaned openFile

}    // End Hpaned::openFile()





///////////////////////////////////////////////////////////////////
// static creation function, for importing class into rapidapp
// or dynamically loading, using VkComponent::loadComponent
///////////////////////////////////////////////////////////////////


VkComponent *Hpaned::CreateHpaned( const char *name, Widget parent ) 
{  
    VkComponent *obj =  new Hpaned ( name, parent );
    return ( obj );
} // End CreateHpaned


///////////////////////////////////////////////////////////////////
// Function for accessing a description of the dynamic interface
// to this class.
///////////////////////////////////////////////////////////////////


// WARNING: This structure is different than that used with 1.1 RapidApp.
// See the RapidApp release notes for details

struct InterfaceMap {
  char  *resourceName;
  char  *methodName;
  char  *argType;
  char  *definingClass; // Optional, if not this class
  void (VkCallbackObject::*method)(...); // Reserved, do not set
};


void *Hpaned::RegisterHpanedInterface()
{ 
    // This structure registers information about this class
    // that allows RapidApp to create and manipulate an instance.
    // Each entry provides a resource name that will appear in the
    // resource manager palette when an instance of this class is
    // selected, the name of the member function as a string,
    // the type of the single argument to this function, and an.
    // optional argument indicating the class that defines this function.
    // All member functions must have the form
    //  
    //     void memberFunction ( Type );
    //
    // where "Type" is one of:
    //    const char *    (Use XmRString)
    //    Boolean         (Use XmRBoolean)
    //    int             (Use XmRInt)
    //    float           (Use XmRFloat)
    //    No argument     (Use VkRNoArg or "NoArg"
    //    A filename      (Use VkRFilename or "Filename")
    //    An enumeration  (Use "Enumeration:ClassName:Type: VALUE1, VALUE2, VALUE3")
    //    A callback      (Use XmRCallback)


    static InterfaceMap map[] = {
    //---- Start editable code block: HpanedUI resource table

      // { "resourceName", "setAttribute", XmRString},
    //---- End editable code block: HpanedUI resource table
      { NULL }, // MUST be NULL terminated
    };

    return map;
} // End RegisterHpanedInterface()






//---- End of generated code

//---- Start editable code block: End of generated code


//---- End editable code block: End of generated code


