
//////////////////////////////////////////////////////////////
//
// Header file for Hpaned
//
//    This file is generated by RapidApp 1.2
//
//    This class is derived from HpanedUI which 
//    implements the user interface created in 
//    RapidApp. This class contains virtual
//    functions that are called from the user interface.
//
//    When you modify this header file, limit your changes to those
//    areas between the "//---- Start/End editable code block" markers
//
//    This will allow RapidApp to integrate changes more easily
//
//    This class is a ViewKit user interface "component".
//    For more information on how components are used, see the
//    "ViewKit Programmers' Manual", and the RapidApp
//    User's Guide.
//////////////////////////////////////////////////////////////
#ifndef HPANED_H
#define HPANED_H
#include "HpanedUI.h"
//---- Start editable code block: headers and declarations


//---- End editable code block: headers and declarations


//---- Hpaned class declaration

class Hpaned : public HpanedUI
{

  public:

    Hpaned ( const char *, Widget );
    Hpaned ( const char * );
    ~Hpaned();
    const char *  className();
    virtual void openFile(const char *);

    static VkComponent *CreateHpaned( const char *name, Widget parent ); 

    //---- Start editable code block: Hpaned public

  class SoXtExaminerViewer *viewer() {return _viewer;}

    //---- End editable code block: Hpaned public



  protected:


    // These functions will be called as a result of callbacks
    // registered in HpanedUI

    virtual void autoToggleCB ( Widget, XtPointer );
    virtual void speedScaleCB ( Widget, XtPointer );

    //---- Start editable code block: Hpaned protected


    //---- End editable code block: Hpaned protected



  private:

    static void* RegisterHpanedInterface();

    //---- Start editable code block: Hpaned private


    //---- End editable code block: Hpaned private


};
//---- Start editable code block: End of generated code


//---- End editable code block: End of generated code

#endif

