
//////////////////////////////////////////////////////////////////////
// This is a driver ViewKit program generated by RapidApp 1.2 

//
// This program instantiates a ViewKit VkApp object and creates
// any main window objects that are meant to be shown at startup.
// Although editable code blocks are provided, there should rarely.
// be any reason to modify this file. Make application-specific
// changes in the classes created by the main window classes
// You can add also additional initialization in subclasses of VkApp
//////////////////////////////////////////////////////////////////////
#include <Vk/VkSoApp.h>

// Headers for window classes used in this program

#include "VkwindowMainWindow.h"

//---- Start editable code block: headers and declarations


//---- End editable code block: headers and declarations


// Fallback resources

static char *fallbackResources[] = {
    "*useSchemes:     all",
    "*sgiMode:        true",
    "*useEnhancedFSB: true",
    "*keyboardFocusPolicy: explicit",
    "*vkwindow*title:  V-Clip Collision Detection",
    //---- Start editable code block: fallbacks

    //---- End editable code block: fallbacks
    NULL
};


void main ( int argc, char **argv )
{
    extern void InitEZ(void);

    InitEZ(); // Only need to force bind EZ library              // for Fix+Continue

    //---- Start editable code block: main initialization

    //---- End editable code block: main initialization

    VkApp::setFallbacks(fallbackResources);

    VkSoApp       *app;

    // Create an application object

    app = new VkSoApp("Vcdemo", &argc, argv); 

    //---- Start editable code block:  post init

    //---- End editable code block:  post init

    // Create the top level windows

    VkSimpleWindow *vkwindow  = new VkwindowMainWindow("vkwindow");
    vkwindow->show();

    //---- Start editable code block:  event loop

    void setup();
    setup();

    //---- End editable code block:  event loop

    app->run ();


}

//---- Start editable code block: End of generated code


//---- End editable code block: End of generated code

