set(OPENHRP_FOUND TRUE)

execute_process(
  COMMAND pkg-config --modversion openhrp3.1
  OUTPUT_VARIABLE OPENHRP_VERSION
  RESULT_VARIABLE RESULT
  OUTPUT_STRIP_TRAILING_WHITESPACE)

execute_process(
  COMMAND pkg-config --modversion openhrp3.2
  OUTPUT_VARIABLE OPENHRP_VERSION
  RESULT_VARIABLE RESULT
  OUTPUT_STRIP_TRAILING_WHITESPACE)

STRING(REGEX REPLACE "^([0-9]+)\\.[0-9]+\\.[0-9]+" "\\1" OPENHRP_VERSION_MAJOR "${OPENHRP_VERSION}")
STRING(REGEX REPLACE "^[0-9]+\\.([0-9])+\\.[0-9]+" "\\1" OPENHRP_VERSION_MINOR "${OPENHRP_VERSION}")
STRING(REGEX REPLACE "^[0-9]+\\.[0-9]+\\.([0-9]+)" "\\1" OPENHRP_VERSION_PATCH "${OPENHRP_VERSION}")

if(NOT RESULT EQUAL 0)
  set(OPENHRP_FOUND FALSE)
else()
  set(OPENHRP_LIBRARY_VERSION "${OPENHRP_VERSION_MAJOR}.${OPENHRP_VERSION_MINOR}")
  message(STATUS "Try to use latest openhrp version = ${OPENHRP_LIBRARY_VERSION}")
endif()

execute_process(
  COMMAND pkg-config --variable=prefix openhrp${OPENHRP_LIBRARY_VERSION}
  OUTPUT_VARIABLE OPENHRP_DIR
  RESULT_VARIABLE RESULT
  OUTPUT_STRIP_TRAILING_WHITESPACE)

if(NOT RESULT EQUAL 0)
  set(OPENHRP_FOUND FALSE)
endif()

execute_process(
  COMMAND pkg-config --cflags openhrp${OPENHRP_LIBRARY_VERSION}
  OUTPUT_VARIABLE OPENHRP_CXX_FLAGS
  RESULT_VARIABLE RESULT
  OUTPUT_STRIP_TRAILING_WHITESPACE)

if(RESULT EQUAL 0)
  string(REGEX MATCHALL "-D.*[^ ;]+" OPENHRP_DEFINITIONS ${OPENHRP_CXX_FLAGS})
else()
  set(OPENHRP_FOUND FALSE)
endif()

execute_process(
  COMMAND pkg-config --cflags-only-I openhrp${OPENHRP_LIBRARY_VERSION}
  OUTPUT_VARIABLE OPENHRP_INCLUDE_DIRS
  RESULT_VARIABLE RESULT
  OUTPUT_STRIP_TRAILING_WHITESPACE)

if(RESULT EQUAL 0)
  string(REGEX REPLACE "-I" ";" OPENHRP_INCLUDE_DIRS ${OPENHRP_INCLUDE_DIRS})
else()
  set(OPENHRP_FOUND FALSE)
endif()

execute_process(
  COMMAND pkg-config --libs openhrp${OPENHRP_LIBRARY_VERSION}
  OUTPUT_VARIABLE OPENHRP_LIBRARIES
  RESULT_VARIABLE RESULT
  OUTPUT_STRIP_TRAILING_WHITESPACE)

if(RESULT EQUAL 0)
  string(REGEX MATCHALL "-L[^ ;]+" OPENHRP_LIBRARY_DIRS ${OPENHRP_LIBRARIES})
  string(REGEX REPLACE "-L" ";" OPENHRP_LIBRARY_DIRS "${OPENHRP_LIBRARY_DIRS}")

  string(REGEX REPLACE "-L[^ ;]+" "" OPENHRP_LIBRARIES ${OPENHRP_LIBRARIES})
  separate_arguments(OPENHRP_LIBRARIES)
else()
  set(OPENHRP_FOUND FALSE)
endif()

if(NOT OPENHRP_FOUND)
  set(OPENHRP_DIR NOT_FOUND)
endif()

execute_process(
  COMMAND pkg-config --variable=idl_dir openhrp${OPENHRP_LIBRARY_VERSION}
  OUTPUT_VARIABLE OPENHRP_IDL_DIR
  RESULT_VARIABLE RESULT
  OUTPUT_STRIP_TRAILING_WHITESPACE)

if(NOT RESULT EQUAL 0)
  set(OPENHRP_FOUND FALSE)
endif()

set(OPENHRP_DIR ${OPENHRP_DIR} CACHE PATH "The top directory of OpenHRP")

if(OPENHRP_FOUND)
  if(NOT OpenHRP_FIND_QUIETLY)
    message(STATUS "Found OpenHRP ${OPENHRP_VERSION} in ${OPENHRP_DIR}")
  endif()
else()
  if(NOT OpenHRP_FIND_QUIETLY)
    if(OpenHRP_FIND_REQUIRED)
      message(FATAL_ERROR "OpenHRP required, please specify it's location.")
    endif()
  endif()
endif()
