/**
 * @file CollisionDetectorService.idl
 * @brief Services for the collision detector
 */
module OpenHRP
{
  
  interface CollisionDetectorService
  {

    /**
     * @brief set tolerance value for collision detector
     * @param link_pair_name name of link pair
     * @param tolerance tolerance
     * @return true if set successfully, false otherwise
     */
    boolean setTolerance(in string link_pair_name, in double tolerance);
  };
};
