#ifndef __EMERGENCYSTOPPER_SERVICE_IDL__
#define __EMERGENCYSTOPPER_SERVICE_IDL__

module OpenHRP
{
  interface EmergencyStopperService
  {
    void stopMotion();
    void releaseMotion();
  };
};

#endif