/**
 * @file KalmanFilterService.idl
 * @brief Services for the kalman filter interface
 */
module OpenHRP
{
  interface KalmanFilterService
  {
    /**
     * @struct KalmanFilterParam
     * @brief KalmanFilter Parameters.
     */
    struct KalmanFilterParam
    {
      double Q_angle;
      double Q_rate;
      double R_angle;
    };

    /**
     * @brief Set KalmanFilter parameters
     * @param i_param is input parameter
     * @return true if set successfully, false otherwise
     */
    boolean setKalmanFilterParam(in KalmanFilterParam i_param);

    /**
     * @brief Get KalmanFilter parameters
     * @param i_param is input parameter
     * @return true if set successfully, false otherwise
     */
    boolean getKalmanFilterParam(out KalmanFilterParam i_param);

  };
};