// -*- coding:utf-8-unix; mode: idl; indent-tabs-mode: nil; c-basic-offset: 2; -*-
#ifndef __NULL_SERVICE_IDL__
#define __NULL_SERVICE_IDL__

module OpenHRP
{
  interface NullService
  {
    void echo(in string msg);
  };
};

#endif