/**
 * @file ReferenceForceUpdaterService.idl
 * @brief Services for the reference force updater interface
 */
module OpenHRP
{
  interface ReferenceForceUpdaterService
  {
      typedef sequence<double, 3> DblSequence3;

      /**
       * @struct ReferenceForceUpdaterParam
       * @brief ReferenceForceUpdater Parameters.
       */
      struct ReferenceForceUpdaterParam
      {
          /// Motion direction to update reference force
          DblSequence3 motion_dir;
          /// frame of motion_dir ("local" or "world").
          /// "local" is coordinate at end effector, and "world" is the coordinate between the feet.
          string frame;
          /// Update frequency [Hz]
          double update_freq;
          /// Update time ratio \in [0,1]
          double update_time_ratio;
          /// P gain
          double p_gain;
          /// D gain
          double d_gain;
          /// I gain
          double i_gain;
      };

      /**
       * @brief Set ReferenceForceUpdater parameters
       * @param i_param is input parameter
       * @return true if set successfully, false otherwise
       */
      boolean setReferenceForceUpdaterParam(in string name, in ReferenceForceUpdaterParam i_param);

      /**
       * @brief Get ReferenceForceUpdater parameters
       * @param i_param is input parameter
       * @return true if set successfully, false otherwise
       */
      boolean getReferenceForceUpdaterParam(in string name, out ReferenceForceUpdaterParam i_param);

      /**
       * @brief Start ReferenceForceUpdater
       * @return true if set successfully, false otherwise
       */
      boolean startReferenceForceUpdater(in string name);

      /**
       * @brief Stop ReferenceForceUpdater
       * @return true if set successfully, false otherwise
       */
      boolean stopReferenceForceUpdater(in string name);
  };
};
