/**
 * @file SoftErrorLimiterService.idl
 * @brief Services for the robot hardware interface
 */
module OpenHRP
{
  interface SoftErrorLimiterService
  {
    /**
     * @brief set the maximum joint servo error angle
     * @param name joint name, part name or "all"
     * @param limit the maximum joint servo error angle[rad]
     */
    void setServoErrorLimit(in string name, in double limit);
  };
};