/**
 * @file TorqueControllerService.idl
 * @brief Services for the torque control interface
 */
module OpenHRP
{
  
  interface TorqueControllerService
  {
    typedef sequence<double> dSequence;    
    typedef sequence<string> StrSequence;

    struct torqueControllerParam {
      double tc; // time constant
      double ke; // for TwoDofController and TwoDofControllerPDModel 
      double kd; // for TwoDofControllerPDModel 
      double ki; // for TwoDofControllerDynamicModel
      double alpha; // for TwoDofControllerDynamicModel
      double beta; // for TwoDofControllerDynamicModel
    };

    /**
     * @brief enable torque controller in specified joint
     * @param jname: target joint name
     * @return true if set successfully, false otherwise
     */
    boolean enableTorqueController(in string jname);

    /**
     * @brief enable torque controller in specified joints
     * @param jnames: target joint names
     * @return true if set successfully, false otherwise
     */
    boolean enableMultipleTorqueControllers(in StrSequence jnames);
    
    /**
     * @brief disable torque controller in specified joint
     * @param jname: target joint name
     * @return true if set successfully, false otherwise
     */
    boolean disableTorqueController(in string jname);

    /**
     * @brief disable torque controller in specified joints
     * @param jnames: target joint names
     * @return true if set successfully, false otherwise
     */
    boolean disableMultipleTorqueControllers(in StrSequence jnames);
      
    /**
     * @brief start torque controller in specified joint
     * @param jname: target joint name
     * @return true if set successfully, false otherwise
     */
    boolean startTorqueControl(in string jname);

    /**
     * @brief start torque controller in specified joints
     * @param jnames: target joint names
     * @return true if set successfully, false otherwise
     */
    boolean startMultipleTorqueControls(in StrSequence jnames);
    
    /**
     * @brief stop torque controller in specified joint
     * @param jname: target joint name
     * @return true if set successfully, false otherwise
     */
    boolean stopTorqueControl(in string jname);

    /**
     * @brief stop torque controller in specified joints
     * @param jnames: target joint names
     * @return true if set successfully, false otherwise
     */
    boolean stopMultipleTorqueControls(in StrSequence jnames);
    
    /**
     * @brief set torque reference to torque controller in specified joint
     * @param jname: target joint name
     * @param tauRef: reference torque
     * @return true if set successfully, false otherwise
     */
    boolean setReferenceTorque(in string jname, in double tauRef);

    /**
     * @brief set torque reference to torque controller in specified joint
     * @param jname: target joint names
     * @param tauRef: reference torques
     * @return true if set all successfully, false otherwise
     */
    boolean setMultipleReferenceTorques(in StrSequence jnames, in dSequence tauRefs);

    /**
     * @brief set torque controller parameters
     * @param i_param: new torque controller param (invariant parameters are expected as 0)
     * @return true if set all successfully, false otherwise
     */
    boolean setTorqueControllerParam(in string jname, in torqueControllerParam i_param);

    /**
     * @brief set torque controller parameters
     * @param i_param: new torque controller param (invariant parameters are expected as 0)
     * @return true if set all successfully, false otherwise
     */
    boolean getTorqueControllerParam(in string jname, out torqueControllerParam i_param);
  };
};
