/**
 * @file WavPlayerService.idl
 * @brief Services for the wav player interface
 */
module OpenHRP
{
  interface WavPlayerService
  {
    /**
     * @brief play a wav file and return when it finishes
     * @param wavfile path of the wav file
     */
    void playWav(in string wavfile);

    /**
     * @brief invoke a thread which plays a wav file and return immediately
     * @param wavfile path of the wav file
     */
    oneway void playWavNoWait(in string wavfile);
  };
};
