/**
 * @file WholeBodyMasterSlaveService.idl
 * @brief Services for the WholeBodyMasterSlave interface
 */
//#include "OpenHRPCommon.idl"
module OpenHRP
{
  
  interface WholeBodyMasterSlaveService
  {
    typedef sequence<double, 3> DblSequence3;
    //typedef sequence<double, 4> DblSequence4;
    typedef double DblArray3[3];
    typedef double DblArray4[4];
    typedef sequence<string> StrSequence;

    /**
     * HumanSync
     */
    struct WholeBodyMasterSlaveParam
    {
        double auto_swing_foot_landing_threshold;
        double foot_vertical_vel_limit_coeff;
        double human_com_height;
        boolean is_doctor;
        boolean set_com_height_fix;
        double set_com_height_fix_val;
        double swing_foot_height_offset;
        double swing_foot_max_height;
        double upper_body_rmc_ratio;
        boolean use_hands;
        boolean use_head;
        boolean use_manipulability_limit;
        boolean disable_lower;
    };
    boolean startCountDownForWholeBodyMasterSlave(in double sec);
    boolean startWholeBodyMasterSlave();
    boolean stopWholeBodyMasterSlave();
    boolean pauseWholeBodyMasterSlave();
    boolean resumeWholeBodyMasterSlave();
    void setWholeBodyMasterSlaveParam(in WholeBodyMasterSlaveParam i_param);
    void getWholeBodyMasterSlaveParam(out WholeBodyMasterSlaveParam i_param);
  };
};
