/**
 * @file WholeBodyMasterSlaveService.idl
 * @brief Services for the WholeBodyMasterSlave interface
 */
//#include "OpenHRPCommon.idl"
module OpenHRP
{
  
  interface WholeBodyMasterSlaveService
  {
    typedef sequence<double, 3> DblSequence3;
    //typedef sequence<double, 4> DblSequence4;
    typedef double DblArray3[3];
    typedef double DblArray4[4];
    typedef sequence<string> StrSequence;

    /**
     * HumanSync
     */
    struct WholeBodyMasterSlaveParam
    {
        double auto_swing_foot_landing_threshold;
        double human_to_robot_ratio;
        double set_com_height_fix_val;
        double swing_foot_height_offset;
        double upper_body_rmc_ratio;
        boolean set_com_height_fix;
        boolean use_head;
        boolean use_upper;
        boolean use_lower;
        StrSequence use_joints;
        StrSequence use_targets;
    };
    boolean startWholeBodyMasterSlave();
    boolean stopWholeBodyMasterSlave();
    boolean pauseWholeBodyMasterSlave();
    boolean resumeWholeBodyMasterSlave();
    void setParams(in WholeBodyMasterSlaveParam i_param);
    void getParams(out WholeBodyMasterSlaveParam i_param);
  };
};
